name: Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: windows-2022
    permissions:
      contents: write

    env:
      Solution_Name: WindBot.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v3

    - name: Restore NuGet packages
      run: nuget restore $env:Solution_Name

    - name: Build
      run: msbuild $env:Solution_Name /t:Build /p:Configuration=Release /p:Platform=x64

    - name: Pack
      run: |
        mkdir dist
        xcopy /e /y bin\Release dist\WindBot\
        xcopy /y BotWrapper\bin\Release\bot.conf dist\
        xcopy /y BotWrapper\bin\Release\load-once.conf dist\
        xcopy /y BotWrapper\bin\Release\bot.exe dist\

    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      with:
        name: windbot-dist
        path: dist

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Download Artifact
      uses: actions/download-artifact@v8
      with:
        name: windbot-dist
        path: dist

    - name: GitHub Release
      env:
        GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        TAG_NAME: "${{ github.ref_name }}"
      run: |
        tar -C dist -czvf WindBot.tar.gz .
        cd dist
        zip -r ../WindBot.zip .
        cd ..
        gh release create "$TAG_NAME" WindBot.tar.gz WindBot.zip --title "$TAG_NAME" --generate-notes

  mono-build:
    runs-on: ubuntu-latest
    container:
      image: mono:6.8.0.123

    env:
      Solution_Name: WindBot.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Build with Mono MSBuild
      run: msbuild "$Solution_Name" /restore /t:Build /p:Configuration=Release /p:Platform=x64

    - name: Fix sqlite dll location
      # Old MSBuild don't process the TargetPath correctly. https://github.com/dotnet/msbuild/pull/6237
      # This is fixed in 16.10 that ships with latest mono.
      run: |
        for arch in x86 x64; do
          source_path="bin/Release/ThirdParty/sqlite/$arch/sqlite3.dll"
          target_dir="bin/Release/$arch"
          if [ -f "$source_path" ]; then
            mkdir -p "$target_dir"
            mv -f "$source_path" "$target_dir/sqlite3.dll"
            echo "Moved $source_path to $target_dir/sqlite3.dll"
          fi
        done

    - name: Upload Mono build artifacts
      uses: actions/upload-artifact@v6
      with:
        name: WindBot-mono
        path: bin/Release/
        if-no-files-found: error
